### ISSUE TITLE
CUDA-capable device(s) is/are busy or unavailable

### ISSUE THREAD

**Issue by LiYueqian-James** [microsoft/superbenchmark#691]
**What's the issue, what's expected?**:
nvidia-smi showed no running process before running SB.
however, after SB started running, got error

[ERROR] Create model with specified precision failed - model: pytorch-gpt2-small, precision: float32, message: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
.
[2025-03-04 00:27:01,537 VM0303145338934:269][base.py:179][ERROR] Run benchmark failed - benchmark: pytorch-gpt2-small, message: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 36, in do_one_step
    data = pin_memory(data, device)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/pin_memory.py", line 57, in pin_memory
    return data.pin_memory(device)
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**How to reproduce it?**:
Azure VM Sku: Standard_NV36ads_A10_v5
OS: canonical:0001-com-ubuntu-server-jammy:22_04-lts:latest
gpudriver: https://download.microsoft.com/download/c/3/4/c3484f19-fe76-4495-a65d-a5222ead9517/NVIDIA-Linux-x86_64-550.144.03-grid-azure.run
Inference config file: can be shared privately.

I can help with setting up the VM environment internally.

**Comment by LiYueqian-James** [comment]
Turns out to be a driver/user side config related issue.

The below code reproduced the same error

import torch
x = torch.randn(1, 1).pin_memory()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
